# Generated by Django 4.1.5 on 2024-07-31 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('displayName', models.CharField(max_length=128)),
                ('bank', models.CharField(choices=[('HDFC', 'hdfc'), ('ICICI', 'icici'), ('SBI', 'sbi')], max_length=128)),
                ('accountNo', models.BigIntegerField(null=True)),
                ('ifscode', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BankAccountTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('tranType', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], max_length=128)),
                ('decription', models.TextField()),
                ('bankAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.bankaccount')),
            ],
        ),
    ]
