# Generated by Django 4.1.5 on 2024-07-31 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='bank',
            field=models.CharField(choices=[('hdfc', 'HDFC'), ('icici', 'ICICI'), ('sbi', 'SBI')], max_length=128),
        ),
        migrations.AlterField(
            model_name='bankaccounttransaction',
            name='tranType',
            field=models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=128),
        ),
    ]
