# Generated by Django 4.1.5 on 2024-10-03 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_alter_bankaccounttransaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccounttransaction',
            name='amount',
            field=models.BigIntegerField(default=0),
        ),
    ]
