# Generated by Django 4.1.5 on 2024-07-31 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('type', models.CharField(choices=[('Home', 'home'), ('Miscellaneous', 'miscellaneous'), ('Travelling', 'travelling'), ('Medical/Learning', 'med_learning'), ('Shopping/Party', 'shop_party'), ('Special', 'special')], max_length=128)),
                ('amount', models.BigIntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
