# Generated by Django 4.1.5 on 2024-07-31 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0002_alter_income_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='type',
            field=models.CharField(choices=[('miniOrange', 'miniorange'), ('Freelance', 'freelance'), ('Dad', 'dad'), ('Invts Sold', 'invts_sold'), ('Refund', 'refund')], max_length=128),
        ),
    ]
