# Generated by Django 4.1.5 on 2024-07-31 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0003_alter_income_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='type',
            field=models.CharField(choices=[('miniorange', 'miniOrange'), ('freelance', 'Freelance'), ('dad', 'Dad'), ('invts_sold', 'Invts Sold'), ('refund', 'Refund')], max_length=128),
        ),
    ]
