# Generated by Django 4.1.5 on 2024-09-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0004_alter_income_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.BigIntegerField(),
        ),
    ]
