# Generated by Django 4.1.5 on 2024-07-31 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('type', models.CharField(choices=[('FD', 'fd'), ('NPS', 'nps'), ('Mutual Fund', 'mf'), ('Stock', 'stock')], max_length=128)),
                ('amount', models.BigIntegerField()),
                ('decription', models.TextField()),
            ],
        ),
    ]
