# Generated by Django 4.1.5 on 2024-07-31 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='type',
            field=models.CharField(choices=[('fd', 'FD'), ('nps', 'NPS'), ('mf', 'Mutual Fund'), ('stock', 'Stock')], max_length=128),
        ),
    ]
