# Generated by Django 4.1.5 on 2024-10-03 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0003_alter_investment_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investment',
            old_name='decription',
            new_name='description',
        ),
    ]
